#!/bin/sh

if [ "$API_PORT" ] ; then
py_code="
from aiohttp import web
app = web.Application()
app.router.add_get('/', lambda _: web.Response(text='Web Server Running...'))
web.run_app(app, host='0.0.0.0', port=$API_PORT, reuse_port=True, print=None)
"
    python3 -q -c "$py_code" & echo "Dummy Web Server Started..."

fi

requirements=("aiohttp>=3.8.4"
"beautifulsoup4>=4.12.2"
"Brotli>=1.0.9"
"gallery_dl>=1.25.7"
"pyrogram>=2.0.106"
"python-dotenv==0.21.0"
"PyExecJS>=1.5.1"
"tenacity>=8.2.2"
"tgCrypto>=1.2.3"
"yt-dlp>=2023.6.22"
)

for req in "${requirements[@]}"; do
    pip install "${req}";
done

python3 -m app